### ISSUE TITLE
set default id by index in json array

### ISSUE THREAD

**Issue by naviialto** [Cutehacks/gel#18]
int JsonListModel::addItem(const QJSValue &item, QString defaultid )
{
.......................
    } else if (item.isObject()) {
		if (!item.hasProperty(m_idAttribute)) {
			if( defaultid.isEmpty() )
			{
				qWarning("Object does not have a %s property", qPrintable(m_idAttribute));
				return row;
			}
			else
				id = defaultid;
		}
		else
			id = item.property(m_idAttribute).toString();
	}
..................

void JsonListModel::add(const QJSValue &item)
{
...........................
            if ((m_dynamicRoles || isFirstItem) && extractRoles(array.value()))
                rolesAdded = true;
			int row = addItem(array.value(), array.name());

**Comment by jrbarron** [comment]
@naviialto Thanks for your suggestion. I have a few questions about this. What is the use case here? Does every item in the list model contain an array or something? Could you maybe show some example data that you want to insert into the model and how you would like it to behave?

p.s. Since you already seem to have some code changes, perhaps this would be better as a pull request?

**Comment by naviialto** [comment]
var testjson =
[{
        "name": "testname",
        "address": "tsetaddress"
    },
    {
        "name": "testname",
        "address": "tsetaddress"
    },
    {
        "name": "testname",
        "address": "tsetaddress"
    }
]

//current code
JsonListModel {
    idAttribute: "???" // i want array index id. 
   Component.onCompleted: add( testjson )  // not found id error. Set id to name. but count is 1
}

// i write code
JsonListModel {
       Component.onCompleted: add( testjson )   // no idAttribute. but code success. count is 3
}

The current code needs an id that is not duplicated.
But testjson does not have an id.
For arrays, it is necessary for id to have a default value of index.

All the code I've changed is posting.

Do you know if you have a property with an index?

**Comment by jrbarron** [comment]
@naviialto The point of `JsonListModel` is that each item can be uniquely identified (by it's `idAttribute`) so that updating the item in the list (eg: from an HTTP GET) will overwrite the existing item. This eliminates duplicates in the list. If you don't have data that can be uniquely identified, then perhaps using the built in `ListModel` is a better option?

I don't think using `array.name()` as the key is the right approach here because if you add another array after, this would overwrite the data which seems incorrect to me? In your above example, if I did this:

```
JsonListModel {
    Component.onCompleted: add( testjson )
    Component.onCompleted: add( testjson )
    // should count be 3 or 6?
}
```

I think an easy workaround for you would be to do something like this:

```
JsonListModel {
    testjson = testjson.map(function(item, index) {
        item.id = index;
        return item;
    })
    Component.onCompleted: add( testjson )
}
```

**Comment by naviialto** [comment]
ye. ok understand. thanks
